version: "3.7"
networks:
  default:
    internal: true
services:
  homarus:
    image: ${REPOSITORY:-islandora}/homarus:${TAG:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-60}
  houdini:
    image: ${REPOSITORY:-islandora}/houdini:${TAG:-latest}
  hypercube:
    image: ${REPOSITORY:-islandora}/hypercube:${TAG:-latest}
  dlq:
    image: ${REPOSITORY:-islandora}/dlq:${TAG:-latest}
    environment:
      DERIVATIVE_DIAL_TIMEOUT_SECONDS: ${DLQ_CONNECT_TIMEOUT_SEC}
    command: -queue ${ACTIVEMQ_DLQ_NAME} -host activemq -pass ${ACTIVEMQ_PASSWORD} -config ${DLQ_HANDLER_CONFIG_LOCATION}
    depends_on:
      - activemq
