version: "3.7"
networks:
  default:
    internal: true
services:
  gemini:
    image: ${REPOSITORY:-islandora}/gemini:${TAG:-latest}
  homarus:
    image: ${REPOSITORY:-islandora}/homarus:${TAG:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME:-60}
  houdini:
    image: ${REPOSITORY:-islandora}/houdini:${TAG:-latest}
  hypercube:
    image: ${REPOSITORY:-islandora}/hypercube:${TAG:-latest}
  milliner:
    image: ${REPOSITORY:-islandora}/milliner:${TAG:-latest}
  recast:
    image: ${REPOSITORY:-islandora}/recast:${TAG:-latest}
