version: "3.7"
networks:
  default:
    internal: true
  gateway:
    name: gateway
services:
  solr:
    tty: true
    restart: ${RESTART_POLICY:-unless-stopped}
    image: ${REPOSITORY:-islandora}/solr:${TAG:-latest}

    # I am not sure why this works but it fixes the problem.
    # This is likely a bug in the buildkit and should be fixed there.
    # But I've spent too much time on this already. Good luck!
    entrypoint: ["bash","-c","apk add procps && s6-setuidgid solr /opt/solr/bin/solr start -f"]

    # No volumes are defined here, other docker-compose.yml files such as
    # docker-compose.demo.yml are expected to extend this definition based
    # on their workflow.
    networks:
      default:
        # Allow services to use the edge name to reference this service.
        # This allows links from the Drupal administration page to lead
        # to the appropriate solr server.
        aliases:
          - solr-${COMPOSE_PROJECT_NAME-isle-dc}.${DRUPAL_SITE_HOST-traefik.me}
          - solr-${COMPOSE_PROJECT_NAME-isle-dc}-${DRUPAL_SITE_HOST-traefik.me}
      gateway: # Do not expose in production.
    labels:
      # Do not expose in production.
      - traefik.enable=true
      - traefik.http.services.${COMPOSE_PROJECT_NAME-isle-dc}-solr.loadbalancer.server.port=8983
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-solr_http.service=${COMPOSE_PROJECT_NAME-isle-dc}-solr
      - traefik.http.routers.${COMPOSE_PROJECT_NAME-isle-dc}-solr_http.entrypoints=http
